### PR TITLE
Verify checksum of freetype dependency

### PR DESCRIPTION
**Pull request by pierwill**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm pretty sure the whole ci-scripts directory here is not used at all (and could be deleted), so I don't think that adding checksum checks makes sense.

Out of interest, how did you find this particular download?

**Comment by pierwill** [comment]
> Out of interest, how did you find this particular download?

I have a script that pulls up every Makefile, Dockerfile, and shell script in a directory. I use this to look for downloads (mostly curl and wget invocations) that lack verification (either checksum or signature).

**Comment by Mark-Simulacrum** [comment]
Okay - I'm happy to see this PR changed to delete that directory (seems nice, in general), but otherwise am inclined to close.

**Comment by nnethercote** [comment]
I think it's better to leave this unchanged. This repo has the entire repositories of numerous other projects copied in, and it feels odd to be tweaking the contents of some of them for no useful purpose.

Good luck finding other repositories where this is useful! The original repository for this change is at https://github.com/servo/webrender, if you haven't already seen that.

**Pull request closed without merging**
