### PR TITLE
Add `unicode-normalization-0.1.19` benchmark

### PR DESCRIPTION
**Pull request by Kobzol**
Time for compiling the whole crate did increase very slightly:
```
        unicode_normalization   unicode-normalization-0.1.19
check   1.22s     1.72s
debug   1.32s     2.01s
opt     1.46s     2.12s
```

Instruction counts have decreased, so it's possible that the increase above is caused by dependencies. In any case, it's quite similar as before:
image

I'm not sure where are those "huge `match` statements that stress the compiler in unusual ways." though. Are they macro generated? :thinking:

### CODE REVIEW

**Comment by nnethercote** [comment]
> I'm not sure where are those "huge `match` statements that stress the compiler in unusual ways." though. Are they macro generated? thinking

Look in `src/tables.rs`.

**Review by nnethercote — APPROVED** [review]
Thanks!

**Comment by nnethercote** [comment]
Please don't merge this until the current site breakage is resolved.

**Comment by Kobzol** [comment]
> > I'm not sure where are those "huge `match` statements that stress the compiler in unusual ways." though. Are they macro generated? thinking
> 
> Look in `src/tables.rs`.

Oh, I was looking at the GitHub diff for the matches and this file was collapsed because it is too big :) Thanks.

**Pull request merged**
