### PR TITLE
Add a benchmark for exhaustive_patterns

### PR DESCRIPTION
**Pull request by Nadrieril**
The `exhaustive_patterns` feature [was measured](https://github.com/rust-lang/rust/pull/79394) to cause significant perf degradation. I minimized the perf regression into this new benchmark, which I hope will be useful when hacking on match checking. I named it after `exhaustive_patterns` because I optimized for that (i.e. large nested structs and enums).
This benchmark gains 30% on check-full when the `exhaustive_patterns` feature is disabled.
Ping https://github.com/rust-lang/rustc-perf/issues/792 and https://github.com/rust-lang/rust/issues/51085.

### CODE REVIEW

**Comment by Nadrieril** [comment]
I don't know what's wrong with the failing CI test. I keep scrolling down without reaching the bottom of the logs

**Comment by Mark-Simulacrum** [comment]
Yeah, CI logs are a bit opaque. Looks like you're missing a Cargo.lock in the newly added test?

```
2020-11-26T05:12:18.8310094Z Preparing match-stress-exhaustive_patterns
2020-11-26T05:12:18.8343075Z [2020-11-26T05:12:18Z INFO  collector::execute] run_rustc with incremental=false, build_kind=Opt, run_kind=None, patch=None
2020-11-26T05:12:18.8457896Z error: a Cargo.lock must exist for this command
2020-11-26T05:12:18.8465325Z Running match-stress-exhaustive_patterns: Opt + [Full, IncrFull, IncrUnchanged, IncrPatched]
2020-11-26T05:12:18.8467236Z [2020-11-26T05:12:18Z DEBUG collector::execute] Benchmark iteration 1/1
2020-11-26T05:12:18.8492777Z [2020-11-26T05:12:18Z INFO  collector::execute] run_rustc with incremental=false, build_kind=Opt, run_kind=Some(Full), patch=None
2020-11-26T05:12:18.8602535Z error: a Cargo.lock must exist for this command
2020-11-26T05:12:18.8619349Z collector error: Failed to benchmark 'match-stress-exhaustive_patterns', recorded: failed to obtain pkgid in '"/tmp/.tmpaxCyjg"'
```

**Comment by Mark-Simulacrum** [comment]
This also needs to update the README in collector/benchmarks to note the newly added test (you can see some existing descriptions there).

**Comment by Mark-Simulacrum** [comment]
I also noted that this doesn't seem to pull in the syn license files, but we should be careful to do so -- I think the easiest thing which should be correct is to just duplicate the license files as is into the directory.

**Comment by Mark-Simulacrum** [comment]
Thanks! This should automatically deploy on the next run or two.

**Pull request merged**
