### PR TITLE
Add testing of `collector profile_local`.

### PR DESCRIPTION
**Pull request by nnethercote**
Because testing is good.

### CODE REVIEW

**Comment by nnethercote** [comment]
I've abused the `&&` operator heavily in this PR. I'd be happy to hear suggestions about better ways to do things.

**Comment by Mark-Simulacrum** [comment]
Hm, I think `set -e` should make us early exit if anything fails in the bash script -- would that work?

**Comment by nnethercote** [comment]
`set -e` is a good idea. I also need to add `kill $PING_LOOP_ID` to the `trap`, to make sure it happens.

**Comment by nnethercote** [comment]
The tests are failing due to an ICE when compiling `collector`:
```
error: internal compiler error: src/librustc_mir/monomorphize/collector.rs:629:54: collection encountered polymorphic constant
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:30:1
```

**Comment by nnethercote** [comment]
The ICE is occurring also for the trivial change in #703. Might be a regression in the latest nightly rustc?

**Comment by Mark-Simulacrum** [comment]
I think this is https://github.com/rust-lang/rust/issues/74614

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rustc-perf/pull/704 should have fixed CI, I'm closing/reopening this to re-trigger it here.

**Comment by Mark-Simulacrum** [comment]
Added some commits that are definitely necessary, but not sure what file it's not finding.

**Comment by nnethercote** [comment]
I think I'll just remove the self-profiling testing, I forgot about needing all the `measureme` stuff. Just testing the eprintln profiling will still give us better coverage than we currently have, and catch a variety of potential problems.

**Comment by nnethercote** [comment]
I rebased to get #704 but somehow I'm still getting the ICE in the tests. /me scratches head

**Comment by Mark-Simulacrum** [comment]
This happened to me multiple times somehow as well, generally I've felt like a number of times my pushes to this PR have just been entirely ignored (i.e., CI runs but on an old commit somehow). My only theory is that GitHub is having problems again..

>  Install latest nightly

It looks like the newly added CI job needs to swap out nightly for beta.

**Comment by nnethercote** [comment]
> It looks like the newly added CI job needs to swap out nightly for beta.

That would be it!

**Comment by nnethercote** [comment]
Progress: the `eprintln` profiling passed the test, but the `perf-record` (which I used to replace the `self-profile`) didn't, due to this:
```
collector error: Failed to profile 'futures' with PerfRecord, recorded: expected success, got exit code: 101

stderr=warning: package replacement is not used: https://github.com/rust-lang/crates.io-index#openssl:0.7.14
   Compiling futures v0.1.0 (/tmp/.tmpo4ALEK)
Error:
The instructions:u event is not supported.
```
The exact invocation is `perf record --call-graph=dwarf --output=perf --freq=299 --event=cycles:u,instructions:u`.

I might just drop the `perf-record` testing.

**Comment by Mark-Simulacrum** [comment]
Presumably whatever VM GitHub Actions puts us in is insufficiently "native" for instruction counting, I guess? Odd that cycles (allegedly) works though.

**Comment by nnethercote** [comment]
This finishes up #681.

**Pull request merged**
