### PR TITLE
Remove GitHub comment footer, and fix table spacing.

### PR DESCRIPTION
**Pull request by nnethercote**
These footnotes make the comment longer but they feel very low value to me.

### CODE REVIEW

**Comment by Kobzol** [comment]
I agree that the footnotes have probably outlived their usefulness.

Regarding the alignment, I think that there were several attempts already to remove it :laughing: I'd just like to point out that this was done on purpose and indeed not all people read the table as Markdown (https://github.com/rust-lang/rustc-perf/issues/1310). But I'm not a stakeholder in this, so I wouldn't block this PR on removing it.

CC @nagisa - how do the PR tables look in plaintext in the current "vertical" format? Is it readable? Does alignment help?

**Review by rylev — COMMENTED** [review]
Seems fine to me, but I agree that we should get some feedback from folks who read this in plaintext.

**Comment by nnethercote** [comment]
I've removed the second commit, I'll deal with that in a separate PR.

**Comment by nnethercote** [comment]
Ok, I fixed the spacing so it looks nice in plaintext.

**Comment by nnethercote** [comment]
Interesting: Firefox renders the emoji in fixed-width text as very slightly less than two chars wide, so the columns don't line up perfectly. Still, it's as close as we're going to get. 

Screen Shot 2022-10-28 at 12 16 51 pm

**Review by Kobzol — APPROVED** [review]

**Pull request merged**
