### PR TITLE
Add triage 2021-05-25

### PR DESCRIPTION
**Pull request by rylev**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Note to self - needs check-in on action items from last week and TWIR.

**Comment by lqd** [comment]
does/should the script also look at max-rss regressions btw ?

**Comment by Mark-Simulacrum** [comment]
It does not; I try to check via the graph most weeks. max-rss is sufficiently noisy that the graph is the only currently good way of detecting max-rss changes, IMO.

**Comment by rylev** [comment]
@Mark-Simulacrum one good thing we could do is have a checklist that all those who do triage should check. I'd be nice to know that we're always checking the same things.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rustc-perf/blob/master/triage/README.md is the place to update, I agree it'd be good.

**Pull request merged**
