### PR TITLE
Add `stm32f4-0.14.0` benchmark

### PR DESCRIPTION
**Pull request by Kobzol**
Time for compiling the whole crate did increase, but not by that much:
```
        stm32f4   stm32f4-0.14.0
check   13.13s     18.63s
debug   14.86s     19.37s
opt     14.13s     20.64s
```
What's quite interesting for this crate is that `check` takes almost as much time as `debug`/`opt`, so the main overhead is in `rustc` and not in LLVM here.

Instruction counts have increased, but seem reasonable (and much higher than for hello world):
image

(Don't open the `Files changed tab`. You have been warned. Better just check the second commit :laughing: ).

### CODE REVIEW

**Review by nnethercote — APPROVED** [review]
Looks good, thank you. Please don't merge this until the current site breakage is resolved.

**Comment by rylev** [comment]
Running this particular benchmark took 10m20s making it the longest running benchmark we have (the second longest `cargo-0.60.0` takes 6m21s). It seems like this cost might be worth it, but are we sure?

**Comment by nnethercote** [comment]
Good question. We run with `"cargo_opts": "--features=stm32f405",`, does disabling that help at all?

**Comment by Kobzol** [comment]
The crate is basically empty if you don't use one of the features (actually it will not even build, `build.rs` will error out). At least one of the STM architectures has to be compiled.

**Pull request merged**
