### PR TITLE
Add cgu instructions count to metrics

### PR DESCRIPTION
**Pull request by csmoe**

### CODE REVIEW

**Comment by Kobzol** [comment]
Hi, where is `cug_instructions` being generated by `rustc`? I cannot find it in its source code anywhere.

**Comment by csmoe** [comment]
> Hi, where is `cug_instructions` being generated by `rustc`? I cannot find it in its source code anywhere.

sorry, it's a typo, should be cgu_instructions

**Comment by csmoe** [comment]
@Kobzol The error in CI check seems not caused by my patch, tried two times.

**Comment by Kobzol** [comment]
Yeah that's unrelated, you can ignore that.

**Review by Kobzol — APPROVED** [review]

**Comment by Kobzol** [comment]
The Windows test will need to be fixed before this can be merged, I'll take a look at it.

**Comment by Kobzol** [comment]
@csmoe Could you rebase on `master` please? The CI issue should be fixed now.

**Pull request merged**
