### PR TITLE
Add `nalgrebra-0.33.0` benchmark

### PR DESCRIPTION
**Pull request by lqd**
This adds `nalgebra` as a benchmark, because it exercises the new trait solver differently than the old solver. We saw that with the [hang](https://github.com/rust-lang/rust/issues/130056) it caused while trying to enable it for coherence.

Tracking its behavior over time will be interesting for enabling the solver for coherence, but also in the future when the trait solver is enabled entirely.

It's not a very costly benchmark to add, here are clean build times (with dependencies)
- cargo check: 10.2s
- cargo build: 10.9s
- cargo build --release: 13.6s

And here are the times for the actual leaf crates benchmarks:
- check full: 4.9s
- debug full: 5.4s
- opt full: 7.6s

I'm opening this as draft for discussion purposes and to see if there are concerns.

### CODE REVIEW

**Comment by Kobzol** [comment]
Thank you! I agree that given the recent hang, it seems useful to add this crate to the suite, it is quite popular and does some crazy things with the trait and const system.

Based on local testing, this should make each benchmark run longer by ~3 minutes.

Btw, the `collector/compile-benchmarks/REUSE.toml` file should be modified with a license for `nalgebra` (not sure why CI didn't catch this...).

**Comment by lqd** [comment]
Dang I had this locally and may have just forgotten to add it before pushing :/ I’ll fix it in a few minutes  after rustconf ends

**Comment by lqd** [comment]
(Done)

**Review by Kobzol — APPROVED** [review]
Maybe we could delete the `tests` directory, it has 10k lines, but no problem with leaving it as-is. Otherwise LGTM.

**Comment by lqd** [comment]
I can do that.

**Comment by nnethercote** [comment]
The [2022 upgrade docs](https://hackmd.io/d9uE7qgtTWKDLivy0uoVQw) have the following:

> - bitmaps-3.1.0 [nnethercote, #1314]
>   - stresses trait stuff, similar to nalgebra-0.30.1
> - nalgebra-0.30.1
>   - bitmaps-3.1.0 has similarities, but is smaller and more extreme, and therefore a better choice

But if the difference between nalgebra and bitmaps has increased with the new solver, seems reasonable to add it.

**Comment by lqd** [comment]
I’m not at a computer where I could open a revert if something goes wrong, but we should merge this soon so that the new PR enabling the new solver can make use of it

**Comment by Kobzol** [comment]
Agree. I just pushed a change that inlined the commit that removed tests, so that we don't have them in git history, hope you don't mind. I'll merge it once CI is green.

**Pull request merged**
