### PR TITLE
database: move bins to separate crates

### PR DESCRIPTION
**Pull request by klensy**
There no way to do bin only dependencies today, so move bins from database; eventually allows to build less unneeded crates via dependencies.

Played around with crate features; hope there no surprise with cargo feature merge.

### CODE REVIEW

**Comment by Kobzol** [comment]
Hi, I wonder what's the motivation for this? Just reducing compile times for the collector/site binaries?

**Comment by klensy** [comment]
Yes, size too; plus more clear separation of functionality/dependencies.

**Comment by Kobzol** [comment]
It seems to remove only two dependencies from collector/site, and doesn't affect their binary sizes a lot (1 KiB for collector it seems), so I'm not sure if it's worth the churn. That being said, it probably doesn't hurt. Let's see what Mark thinks.

**Comment by klensy** [comment]
No immediate effect, yes.

**Comment by Mark-Simulacrum** [comment]
My sense is that this isn't worth the additional complexity.

**Comment by klensy** [comment]
Okay.

**Pull request closed without merging**
