### PR TITLE
feature(compare) Add option to hide raw data, and improve formatting

### LINKED ISSUE #998: Remove the absolute test result numbers from the comparison page
The comparison page provides two columns with the absolute numbers (in milliseconds?) of the two artifacts being compared. I never look at these numbers since it's only important what the difference between them is. Perhaps these can be removed and more useful data (e.g., the severity number proposed in #997) could be used instead. 

image

### PR DESCRIPTION
**Pull request by homersimpsons**
fixes #998

### CODE REVIEW

**Comment by homersimpsons** [comment]
image
image

**Comment by Mark-Simulacrum** [comment]
It looks like the column headers are pretty poorly aligned - that might be something to tackle in a different PR, since it appears pre-existing, but seems worth fixing. Probably needs to be played with to make it look good.

**Comment by homersimpsons** [comment]
Yes, the headers are left-aligned while the content are centered in the cell. I'm no expert in UI so I do not know which content should be aligned to which side ....

**Comment by Mark-Simulacrum** [comment]
I would match the alignment of the values to start.

**Comment by Mark-Simulacrum** [comment]
@homersimpsons I think it'd be helpful to move the toggle for displaying raw values into the Filter box -- that takes up less vertical space, and I don't think it's inherently a different "kind" of toggle -- at least not enough to warrant a separate box.

**Comment by homersimpsons** [comment]
I can do that, the idea was that this checkbox do not change the displayed results but only the way they are displayed

**Pull request merged**
