### PR TITLE
Add summary

### PR DESCRIPTION
**Pull request by rylev**
Adds summary above benchmark tables

image

### CODE REVIEW

**Comment by lqd** [comment]
it would be good to vertically align these icons

**Comment by rylev** [comment]
@lqd thoughts?
image

**Comment by lqd** [comment]
I would _personally_ increase the right spacing between the value and the icons, and try to horizontally center the value + icon container to the columns below. But there's no need to spend time on this specifically, it looks fine as-is and already provides value to users.

**Comment by rylev** [comment]
I agree regarding the spacing between the value and icons. As for aligning with the columns below, I'd like to avoid that since it visually implies that the values are related (which they're not). Perhaps having more a visual separator between the table and the summary could make this look cleaner. 

Going to merge any way. At some point, we can do another visual cleanup.

**Pull request merged**
