### PR TITLE
Allow zooming with mouse wheel in graphs

### PR DESCRIPTION
**Pull request by Kobzol**
I took the mouse wheel zoom code from https://leeoniya.github.io/uPlot/demos/index.html.

https://github.com/rust-lang/rustc-perf/assets/4539057/03c69c61-4fae-4c2f-9f99-ad9d650f75f8

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This seems okay. One question: does this break scrolling through the page as a whole? Do you need to stay "between" graphs or so?

**Comment by Kobzol** [comment]
Yes, you do indeed need to stay "outside of the graphs" to scroll the page.

**Review by Mark-Simulacrum — APPROVED** [review]
I'm okay trying this but we may want to revert if the scrolling interference is too bad.

**Comment by Kobzol** [comment]
Ok, let's see :)

**Comment by lqd** [comment]
Once people have had a chance to experience it, let's gather feedback. (As of now, scrolling interference is somewhat noticeable for me, we'll see over time, or how others feel about it)

**Pull request merged**
