### PR TITLE
Allow benchmarking and profiling stable benchmarks

### PR DESCRIPTION
**Pull request by Kobzol**
By adding a `--category` flag to `bench_local` and `profile_local`.

Fixes: https://github.com/rust-lang/rustc-perf/issues/1777

### CODE REVIEW

**Comment by Nadrieril** [comment]
Thanks for making this! This solves my problem nicely

**Comment by nnethercote** [comment]
Should it be `Primary,Secondary` to match e.g. `Debug` and `Full`? Otherwise, looks good.

**Comment by Kobzol** [comment]
Yes, that would be a bit better match, but for that we'd have to rename the categories in the compile benchmarks JSON files on disk (since these use the lowercase name), and I didn't want to do that in this PR, seemed like an unnecessarily invasive change.

**Comment by nnethercote** [comment]
Is there some way to change this:
```
#[arg(long, value_parser = EnumArgParser::<Category>::default(), default_value = "primary,secondary")]
```
so that we can use upper case on the command line but then it gets converted to lower case internally to match the existing JSON?

**Comment by Kobzol** [comment]
Turns out that there is :) I thought that we use `serde` for parsing the CLI values, but that is not the case, so it was easy to change the field naming for `serde`/`clap` separately. Thanks!

**Review by nnethercote — APPROVED** [review]

**Comment by nnethercote** [comment]
👍

**Pull request merged**
