### PR TITLE
Improve triage report script and add a test

### PR DESCRIPTION
**Pull request by ecstatic-morse**
A rewrite of my first draft. I fixed some bugs, hit it with a formatter and made the generated reports a bit more complete. I'll use this for triage on Monday. 

Also adds a `ci` script for rudimentary testing. Looks like you'll have to enable it in the dashboard though?

### CODE REVIEW

**Comment by ecstatic-morse** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Hm, what dashboard do you mean? I think probably the easiest is to add it to ci/check-profiling.sh -- just calling it from there should be fine. We already have quite a few builders so adding another quick one probably wouldn't be too helpful.

**Comment by ecstatic-morse** [comment]
I meant adding it to the list of CI tasks. I can invoke it from `check-profiling` though.

**Comment by Mark-Simulacrum** [comment]
CI tasks are all managed through .github/workflows/ci.yml I think, so no dashboard involved there :)

That looks good though, will wait for that builder to pass and will merge.

**Comment by ecstatic-morse** [comment]
> CI tasks are all managed through .github/workflows/ci.yml I think, so no dashboard involved there :)

Whoops. `rg '\bci/\b'` let me down.

**Comment by ecstatic-morse** [comment]
@Mark-Simulacrum Should be good to go now.

**Pull request merged**
