### PR TITLE
Remove `ripgrep`

### PR DESCRIPTION
**Pull request by Kobzol**
It was superseded by `ripgrep-13.0.0`.

### CODE REVIEW

**Comment by nnethercote** [comment]
@rylev You have this "[Merge branch 'master' into ripgrep-remove](https://github.com/rust-lang/rustc-perf/pull/1232/commits/cbb8a8a7facf8bbac31d05cd068ef187078b52b0)" commit. There was a similar one you added to #1217. I haven't seen this style of updating PRs before, I found it confusing. Is there anything wrong with a normal rebase and repush?

**Comment by rylev** [comment]
No, this is what GitHub does when you fix merge conflicts through the GitHub API. We haven't been particularly picky with git history in the past, but I'm more than happy to stop doing this, and rely on rebasing instead (it's just slightly less convenient).

**Comment by nnethercote** [comment]
Ok, thanks for the info. I was certainly surprised to see commits from others being added to my PR, and I do like version history to be clean where possible, so I have a personal preference for rebasing.

**Comment by rylev** [comment]
@nnethercote @Kobzol I've rebased. Sorry for the confusion!

**Review by nnethercote — APPROVED** [review]

**Pull request merged**
