### PR TITLE
cc @rust-lang/wg-compiler-performance on master perf regressions.

### PR DESCRIPTION
**Pull request by nnethercote**
To get more visibility on regressions, and earlier.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I'm not entirely opposed, though I do worry a little about diffusing responsibility - might be seen as a sign that folks don't need to do anything if we've already been pinged. Not sure how to best balance that.

**Comment by nnethercote** [comment]
Previous complaints about the github comment have included:
- it's too long
- people don't read it
- if they read it, they don't understand it, and/or don't take action

But now the concern is about a potential person who does read and understand the message, and would have taken action, but the addition of a single "cc" at the bottom causes them to behave differently? I consider that unlikely.

In contrast to this possible effect, there will be a definite effect: several interested people will get CC'd immediately on all regressions. This makes it much more likely that something will happen before weekly triage, making life easier for triagers.

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Well, let's try it. As I mentioned on the other PR, I'm generally happy to experiment here, though would love to put some work into tracking effectiveness of our comment strategy (probably along "author/reviewer do some triage work" lines).

**Comment by nnethercote** [comment]
https://github.com/rust-lang/rust/pull/99123 is the first example of this change having an effect. I never would have seen that PR previously :)

**Pull request merged**
