### PR TITLE
Add empty `[workspace]` to allows for building benchmarks locally

### PR DESCRIPTION
**Pull request by rylev**

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Ah, looks like a rebase error over a just-pushed patch to ctfe-stress? https://travis-ci.com/github/rust-lang/rustc-perf/jobs/302004073#L1266

**Comment by rylev** [comment]
Now the tests are failing due to the issue fixed in #639

**Comment by Mark-Simulacrum** [comment]
webrender is defining workspace twice, looks like

**Comment by Mark-Simulacrum** [comment]
webrender-wrench as well

**Pull request merged**
