### PR TITLE
Add CSS parsing runtime benchmark

### PR DESCRIPTION
**Pull request by Kobzol**
This time it's a bit more realistic benchmark. It benchmarks a CSS parser from Servo. I took a big CSS file (500 KiB minified) from Facebook and use an inflated version of it as the input workload.

```
Finished css/css-parse-fb (1/1)
    [Instructions]: min:   1,494,033,457    mean:    1,495,484,195    stddev:     729,403
          [Cycles]: min:     865,386,053    mean:      923,950,913    stddev:  94,493,454
  [Wall time [µs]]: min:         216,808    mean:          239,945    stddev:      23,147
   [Branch misses]: min:       2,871,605    mean:        2,975,395    stddev:     152,240
    [Cache misses]: min:       4,287,881    mean:        4,779,429    stddev:     781,760
```

### CODE REVIEW

**Comment by nnethercote** [comment]
> I took a big CSS file (500 KiB minified) from Facebook and use an inflated version of it as the input workload.

What's the specific meaning of "inflated" here?

**Comment by Kobzol** [comment]
A larger versiom of that file, created by repeating its contents N times.

**Comment by nnethercote** [comment]
Could the benchmark just iterate N times instead?

**Comment by Kobzol** [comment]
Of course, that's another solution. It's just a bit more fragile in my view, since we need to make sure that the compiler will not optimize the loops away.

**Comment by nnethercote** [comment]
Read it from the file and then duplicate it ten times in memory?

**Comment by Kobzol** [comment]
Yeah, that's what currently happens (https://github.com/rust-lang/rustc-perf/pull/1655/files#diff-bc608464de804456d49a923fbb68f2ced93ea41d17793d22e5b3ae7aea4d7519R11).

**Review by nnethercote — APPROVED** [review]
Oh, I thought the file contained ten copies of the data. Duplicating it in memory seems fine.

**Pull request merged**
