### PR TITLE
Add combine based benchmark to catch exponential trait selection

### PR DESCRIPTION
**Pull request by Marwes**
Similar to #588 but shows a newer regression and without pulling in `combine` itself.

Reduced to run in ~1.5s locally, could be lowered or increased by adding more parsers to the chain.

### CODE REVIEW

**Comment by Marwes** [comment]
cc https://github.com/rust-lang/rust/issues/68666

**Comment by nnethercote** [comment]
You said "newer regression" -- is there another regression I'm not aware of?

**Comment by Marwes** [comment]
https://github.com/rust-lang/rust/issues/67454 and https://github.com/rust-lang/rust/issues/68666 is the ones I refer to, but I probably should not have used regression here. The issues contain practically the same code, only the `Parser` trait has been altered slightly as one is based on combine-3 and the newer on combine-4.

So it has regressed between `combine` versions, but it hasn't regressed between rust versions. Sorry for the confusion!

**Comment by Mark-Simulacrum** [comment]
I'll leave this up to @nnethercote to decide on merging or not, I'm personally not sure but have no specific concerns.

**Comment by Marwes** [comment]
It might be better to merge this after https://github.com/rust-lang/rust/issues/68666 has been fixed, in which case the number of "parser"s could be increased without penalty to the benchmarks.

**Comment by nnethercote** [comment]
> It might be better to merge this after [rust-lang/rust#68666](https://github.com/rust-lang/rust/issues/68666) has been fixed

My understanding is that #68666 (and #67454) were both fixed by #67471, which reverted the changes from #66405 that caused the regression. Furthermore, the regression fix was backported to beta. (#68666 was not marked as fixed, though; I did that just now.)

So I think you could increase the number of parsers safely now. But 1.5s sounds fine, and as long as it demonstrates the original regression (i.e. the old code is drastically slower) I think the current number of parsers should be fine.

**Comment by Marwes** [comment]
> So I think you could increase the number of parsers safely now. But 1.5s sounds fine, and as long as it demonstrates the original regression (i.e. the old code is drastically slower) I think the current number of parsers should be fine.

I can't, since this is a separate performance issue.

**Comment by rylev** [comment]
Going to close since this is a bit stale. Feel free to reopen if you'd like to continue working on this (or if you think this should be rebased and re-reviewed).

**Pull request closed without merging**
